version: '3.8'
services:
  inventory-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventorydb
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
    environment:
      - GATEWAY_PORT=3000

volumes:
  mongo-data: